### PR TITLE
fix deadline square bracket

### LINKED ISSUE #234: [PE-D] Tag not shown in immediate feedback box
Steps to recreate:
1) Add an event task with the following input:
event title: go home date:30-10-2020 from:09:00 to:10:00 desc: homework tag:1234

Expected in the feedback box:

New event added: go home From: 30-10-2020 09:00 To: 30-10-2020 10:00 Description: homework Tag:1234

Actual:

Tag description is missing

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yongmingyang/ped#3

### LINKED ISSUE #239: [PE-D] Optional Items cannot be left blank for deadline
User guide states that items in square bracketes are optional fields. However, attempting to create a deadline without the optional fields results in an error.

Steps fo reproduce:
1. Create a deadline with the following command: `deadline title:BDeadline`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: boundtotheearth/ped#2

### PR DESCRIPTION
**Pull request by BobbyZhouZijian**
fixes #239 
fixes #234

### CODE REVIEW

File: src/main/java/seedu/address/model/task/deadline/Deadline.java [hunk 1]
```diff
@@ -156,12 +156,14 @@ public int hashCode() {
     @Override
     public String toString() {
         final StringBuilder builder = new StringBuilder();
+
+        // attributes that are neglected are hided
```
Comment (MarcTzh) [inline src/main/java/seedu/address/model/task/deadline/Deadline.java]: hidden

File: src/main/java/seedu/address/model/task/event/Event.java [hunk 2]
```diff
@@ -140,14 +141,16 @@ public String toString() {
         if (isLesson) {
             builder.append("Lesson: ");
         }
+
+        // attributes that are neglected are hided
```
Comment (MarcTzh) [inline src/main/java/seedu/address/model/task/event/Event.java]: ^

**Review by MarcTzh — COMMENTED** [review]
nits

**Review by MarcTzh — APPROVED** [review]
LGTM
