### PR TITLE
Beining/fix end time ealier than start time bug

### LINKED ISSUE #240: [PE-D] Event allows to: time before from: time
Event command allows the user to enter a to: time that is before the from: time, and causes the time analysis to display negative values

Steps to reproduce:
1. Create a event with the command `event title:CEvent date:28-10-2020 from:20:00 to:10:00`

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: boundtotheearth/ped#3

### PR DESCRIPTION
**Pull request by dearvae**
fix #240

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EventCommandParser.java [hunk 1]
```diff
@@ -56,5 +63,11 @@ public EventCommand parse(String args) throws ParseException {
         return new EventCommand(event);
     }
 
+    /**
+     * Returns true if the start time is before the end time.
+     */
+    private static boolean isStartTimeBeforeEndTime(LocalDateTime startTime, LocalDateTime endTime) {
```
Comment (MarcTzh) [inline src/main/java/seedu/address/logic/parser/EventCommandParser.java]: hmm i already implemented this in lessonCommandParser, no repeated code, abstract this method out if needed

**Comment by BobbyZhouZijian** [comment]
CI failed. Please check the details and fix them.

**Review by BobbyZhouZijian — APPROVED** [review]
LGTM
