### PR TITLE
Beining/done command fix

### LINKED ISSUE #143: done command input same indexes
when user type same index e.g: done 2 2 
current behaviour is that it will still mark the task done, but we want it to 
give an error message "please do not include duplicate indexes"

### LINKED ISSUE #144: done command on already completed task
should have a message alert the user the task is already done and do not execute the command.
if user supply more many indexes, and one of the index represent a task that is on completed state, the whole command will not be executed and throws an exception with a error message.

### PR DESCRIPTION
**Pull request by dearvae**
fix #144 #143

### CODE REVIEW

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 1]
```diff
@@ -9,5 +9,8 @@
     public static final String MESSAGE_INVALID_COMMAND_FORMAT = "Invalid command format! \n%1$s";
     public static final String MESSAGE_INVALID_TASK_DISPLAYED_INDEX = "The task index provided is invalid";
     public static final String MESSAGE_TASKS_LISTED_OVERVIEW = "%1$d tasks listed!";
+    public static final String MESSAGE_DUPLICATE_TASK_INDEX = "Please do not include duplicate indexes/";
```
Comment (BobbyZhouZijian) [inline src/main/java/seedu/address/commons/core/Messages.java]: I think there's an extra '/'

**Review by BobbyZhouZijian — COMMENTED** [review]
Can you update the UG also?

**Comment by BobbyZhouZijian** [comment]
image
The error message doesn't quite match the actual error.

**Comment by BobbyZhouZijian** [comment]
I think also need to update the DG

**Review by BobbyZhouZijian — APPROVED** [review]
LGTM
