### PR TITLE
Beining/Deadline command fix bugs

### LINKED ISSUE #221: [PE-D] Improve error message for invalid date time for adding deadline tasks
Small nits to pick, but error message could be clearer for invalid date time inputs for adding deadline tasks.

Figure 1: Adding a task with invalid time '18:60'

Figure 2: Command entered and error message

The error message could be slightly clearer to indicate what are the valid ranges, etc. Not sure if it is good to use 'DateTime' in error message as users may not have heard of the Java class! Perhaps a more simple english term like 'Date & Time' is clearer.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: sogggy/ped#7

### LINKED ISSUE #228: [PE-D] Mismatch of deadline command format and actual command format
The user guide states the following format 

the format states that `desc` and `datetime` are optional but does not match with the error message on the app

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ryanlimjr/ped#1

### LINKED ISSUE #232: [PE-D] Space before title prevents deadline to be added
This bug occurred when trying to add a deadline to the task list. I am not sure if this is intended, but here are the steps to reproduce:

Input to interface:
deadline title: go home description: what is the square brackets for? datetime:30-10-2020 19:00

Expected:
New deadline added: go home Done by: 30-10-2020 19:00

Actual:

Edit:
I realized there was a difference in the usage of description in the User Guide. The format stated the use of desc:description, while the explanation in bullet points used description:Description. May want to take note of this

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: yongmingyang/ped#1

### LINKED ISSUE #235: [PE-D] Deadline with the same title cannot be added.
Steps to recreate:
1) Add a deadline task with the following input:
deadline title: Tutorial 1 desc: finish up tutorial 1 for CS1234 datetime: 01-01-0001 10:00 tag: CS1234

2) Add another deadline task with the same name, but different module code:
deadline title: Tutorial 1 desc: finish up tutorial 1 for CS2345 datetime: 01-01-0001 10:00 tag: CS2345

Expected:
Both task to be added even though they have the same title. This is because it is possible to have both different tutorial 1 from different modules.

Actual:

Also, you may want to take note that the year of 0001 can be added. I'm not sure if this is intended.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yongmingyang/ped#4

### PR DESCRIPTION
**Pull request by dearvae**
fix #221 fix #232  fix #235 fix #228

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/DateTimeUtil.java [hunk 1]
```diff
@@ -16,7 +16,7 @@
     public static final String TIME_CONSTRAINTS =
             "Time should be a valid time in the format of HH:mm.";
     public static final String DATE_TIME_CONSTRAINTS =
-            "DateTime should be a valid date and time in the format of dd-MM-yyyy HH:mm.";
+            "DateTime should be a valid date and time in the format of dd-MM-yyyy HH:mm. eg.29-11-2020 23:59";
```
Comment (MarcTzh) [inline src/main/java/seedu/address/commons/util/DateTimeUtil.java]: e.g.

File: src/main/java/seedu/address/logic/commands/DeadlineCommand.java [hunk 2]
```diff
@@ -20,8 +20,8 @@
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a deadline to PlaNus.\n"
             + "Parameters: "
-            + PREFIX_TITLE + "TITLE "
-            + PREFIX_DATE_TIME + "DEADLINE_DATE_TIME "
+            + PREFIX_TITLE + "TITLE \n"
```
Comment (MarcTzh) [inline src/main/java/seedu/address/logic/commands/DeadlineCommand.java]: wont the user have to scroll down a lot to view the error message

File: src/main/java/seedu/address/model/task/deadline/Deadline.java [hunk 3]
```diff
@@ -107,10 +107,11 @@ private boolean isSameDeadline(Deadline otherDeadline) {
         if (otherDeadline == this) {
             return true;
         }
-
         return otherDeadline != null
                 && otherDeadline.getTitle().equals(getTitle())
-                && otherDeadline.getDeadlineDateTime().equals(getDeadlineDateTime());
+                && otherDeadline.getDeadlineDateTime().equals(getDeadlineDateTime())
```
Comment (MarcTzh) [inline src/main/java/seedu/address/model/task/deadline/Deadline.java:112]: This is repeated code, just renamed in both deadline and events, since both are a sub class of task, implement these methods in task and you can override later on

File: src/test/java/seedu/address/model/task/TaskTest.java [hunk 4]
```diff
@@ -37,15 +37,15 @@ public void isSameTask() {
...
+        // same title, same dateTime, different attributes -> returns false
         editedAlice = new DeadlineBuilder(DEADLINE1).withDescription(VALID_DESCRIPTION_BOB)
                 .withTag(VALID_TAG_HUSBAND).build();
-        assertTrue(DEADLINE1.isSameTask(editedAlice));
+        assertFalse(DEADLINE1.isSameTask(editedAlice));
 
 
-        // same title, same dateTime, same type, different attributes -> returns true
+        // same title, same dateTime, different attributes -> returns false
         editedAlice = new DeadlineBuilder(DEADLINE1).withTag(VALID_TAG_HUSBAND).build();
```
Comment (MarcTzh) [inline src/test/java/seedu/address/model/task/TaskTest.java]: use the tags i have in commandTestUtil, do not use old tags from AB3

**Review by BobbyZhouZijian — APPROVED** [review]
LGTM
